#!/bin/bash

s="$1"

if [ -z "$s" ]; then
  echo ",0"
  exit 0
fi

max_char=""
max_lng=0
curr_char=""
curr_lng=0

for (( i=0; i<${#s}; i++ )); do
  char="${s:$i:1}"

  if [ "$char" = "$curr_char" ]; then
    ((curr_lng++))
  else
    if [ $curr_lng -gt $max_lng ]; then
      max_char="$curr_char"
      max_lng=$curr_lng
    fi

    curr_char="$char"
    curr_lng=1
  fi
done

if [ $curr_lng -gt $max_lng ]; then
  max_char="$curr_char"
  max_lng=$curr_lng
fi

echo "$max_char,$max_lng"
