#!/usr/bin/env bash

# In this kata you should simply determine, whether a given year is a leap year or not. In case you don't know the rules, here they are:

# Years divisible by 4 are leap years,
# but years divisible by 100 are not leap years,
# but years divisible by 400 are leap years.
# Tested years are in range 1600 ≤ year ≤ 4000.

# Echo out 1 if year passed in is a leap year, or 0 otherwise.

kata() {
    year=$1
    if (($year % 400 == 0)); then
        echo 1
        exit 0
    elif (($year % 100 == 0)); then
        echo 0
        exit 0
    elif (($year % 4 == 0)); then
        echo 1
        exit 0
    fi

    echo 0
}
